### PR TITLE
Add the latest supported ruby version to RVM version matrix

### PR DESCRIPTION
**Pull request by coreyja**
All of the currently supported ruby versions are officially EOL, so this adds CI testing for the latest patch version of all supported ruby minor versions. This did not require any code changes to make the tests pass, so it seems easy enough to add this to prevent any regressions in newer ruby versions. Let me know if there's anything else you need in order to accept this change!

Copied from PR to upstream here: https://github.com/Shopify/statsd-instrument/pull/151

/domain @effron 
/no-platform

### CODE REVIEW

**Comment by effron** [comment]
/domain @effron 
<<domainLGTM!

**Comment by effron** [comment]
hm since these are actually my commits, maybe someone else should lgtm it!

**Comment by coreyja** [comment]
<< domain LGTM

We chatted offline and decided we will BOTH LG this PR and that feels good since we both contributed!

**Comment by coreyja** [comment]
Nanda?

**Pull request merged**
